%%
mean(abs(d - mean(d, "all")), "all")

%% Radial Average
function Rx = radial_average(X)
    % Given a (2N-1)x(2N-1) matrix of 2D correlations (i.e. as generated by
    % X = xcorr2(im) where im is a NxN image), compute averages over
    % all points (j,k) with equal distance r = sqrt((j-N)^2 + (k - N)^2) from
    % the center entry (N,N) of the matrix.
    [P, Q] = size(X);
    if P ~= Q || rem(P, 2) ~= 1
        error("Matrix X must be of dimension (2N - 1)x(2N - 1) for some N>0.")
    end
    N = (P + 1) / 2;
    M = floor(N * sqrt(2)) + 1;
    sums = zeros(M, 1);
    counts = zeros(M, 1);
    for j = 1:P
        for k = 1:P
            d = sqrt((j-N)^2 + (k-N)^2);
            d_index = floor(d) + 1;
            sums(d_index) = sums(d_index) + X(j,k);
            counts(d_index) = counts(d_index) + 1;
        end
    end
    % Each distance will correspond to at least one entry of X, 
    % so divide by 0 isn't a concern.
    Rx = sums ./ counts;

end

function Rxx = autocov(x)
    [N, M] = size(x);
    if N ~= M
        error("input must be square")
    end
    Rxx = xcorr2(x);
    % Divide correlation by the number of
    % samples averaged over to compute the sample
    % covariance.
    counts = zeros(size(Rxx));
    for i = 1:(2*N-1)
        for j = 1:(2*N-1)
            count_x = min(N, i) - max(0, i - N);
            count_y = min(N, j) - max(0, j - N);
            counts(i,j) = count_x * count_y;
        end
    end
    Rxx = Rxx ./ counts;
end

Rx = radial_average(xcorr2(d));
Rx = Rx(1:256);
Rx = Rx - Rx(end);
Rx = Rx * Rxx_est(1) / Rx(1);
figure()
plot(Rxx_est)
hold on
plot(Rx)
legend(["Rxx_est", "Computed estimate"])



%% New radial estimate about a single point
function Rx = radial_correlation(X, ci, cj)
    % Given a MxN matrix of 2D correlations, compute the
    % expectation E[xy] where x = X(ci, cj) is the evaluation at some
    % center point of the image X and y = X(i,j) is the set of points a
    % distance r = sqrt((i-ci)^2 + (j-cj)^2) from the given center point.
    [M, N] = size(X);
    if ci > M || ci < 1
        error("ci must be in interval [1,M] where M = size(X,1).")
    elseif cj > N || cj < 1
        error("cj must be in interval [1,N] where N = size(X,2).")
    end

    max_x_dist = max(ci, M-ci);
    max_y_dist = max(cj, M-cj);
    D = floor(sqrt(max_x_dist^2 + max_y_dist^2)) + 1;

    sums = zeros(D, 1);
    counts = zeros(D, 1);
    for i = 1:M
        for j = 1:N
            d = sqrt((i - ci)^2 + (j - cj)^2);
            d_index = floor(d) + 1;
            sums(d_index) = sums(d_index) + X(ci, cj) * conj(X(i,j));
            counts(d_index) = counts(d_index) + 1;
        end
    end
    % Each distance will correspond to at least one entry of X, 
    % so divide by 0 isn't a concern.
    Rx = sums ./ counts;
    % Rx = sums;
end

new_Rx = radial_correlation(d, 257, 257);
new_Rx = new_Rx(1:256);
new_Rx = new_Rx - new_Rx(end)
new_Sxx = spectrum2d_from_autocor1d(new_Rx, true);
figure()
imagesc(10 * log10(new_Sxx));
colormap("jet(256)");
title("GOES Hurricane imagery Spectrum (256-level")
colorbar
%% Rx
figure()
plot(new_Rx)





%% Compute SNR
function Rxx = xcorr2_same(x)
    [N, M] = size(x);
    % Output size will be (2N - 1) x (2M - 1) with the (N,M) entry
    % corresponding to Rxx(\tau=0, \mu=0). We therefore select
    % indices (N - floor(N/2)) <= \tau < (N + ceil(N/2)) which correspond
    % to the greatest overlap
    Rxx = xcorr2(x);
    Rxx = Rxx( ...
        N - floor(N/2) : N + ceil(N/2) - 1,    ...
        M - floor(M/2) : M + ceil(M/2) - 1     ...
    );
end

function Sxx = spectrum2d(x)
    [N, M] = size(x);
    Rxx = xcorr2_same(x);
    Sxx = fftshift(abs(fft2(Rxx)));
    % Normalize by power
    P = Rxx(floor(N/2) + 1, floor(M/2) + 1);
    Sxx = Sxx * P / sum(sum(Sxx));
end

function plot_2d_db(im)
    imagesc(20 * log10(im));
    colormap("jet(256)");
    colorbar
end

n = dpn - d;
Snn = spectrum2d(n);

figure()
plot_2d_db(Snn)
title("Noise Spectrum")

%%
Sxx = spectrum2d(d);

figure()
plot_2d_db(Sxx)
title("Spectrum of signal")



%%
w = zeros(N, N);
sigma_smoothing = 3;
center = 30;
for i=1:N
    for j = 1:N
        w(i, j) = 1 / (2 * pi * sigma_smoothing^2) * exp( ...
            -((i - center)^2 + (j - center)^2) / (2*sigma_smoothing^2));
    end
end


W = abs(fftshift(fft2(w)));
figure()
plot_2d_db(w)
% plot_2d_db(w + paddata(pattern, [N, N]))
clim([-140, 1])
figure()
plot_2d_db(abs(W))


%%
figure()
image(angle(W))
colormap(repmat(linspace(0, 1, pi)', 1, 3));


%%
figure()
image(angle(d_est))
colorbar
colormap(repmat(linspace(0, 1, pi)', 1, 3));


%% Can we use W to convolve the raw image?

conv_d = freq_space_filter(d, W);
figure()
image_gray(conv_d)

figure()
plot_2d_db(abs(conv_d - dc))

%% Maybe the inversion of 1/W is sensitive in the frequency space, but
% will work if we ifft it?
w_dconv = ifft(ifftshift(1./W));

figure()
plot_2d_db(abs(1./W))
figure()
plot_2d_db(abs(w_dconv))

%% Is our convolved image close to the provided one?
% The padding seems to totally mess up the convolution...
% conv_d = conv2(d, w, "same");
% This replicates the provided data nearly exactly.
conv_d = conv2(d, pattern, "same");

figure()
plot_2d_db(abs(conv_d - dc))

%% Maybe the issue above is that we are using the wrong slice with the "same" argument
conv_d = conv2(d, w, "full");
start = (P-1)/2 + 1;
end_i = start + N - 1;
conv_d = conv_d(start:end_i, start:end_i);
figure()
image_gray(conv_d)

figure()
plot_2d_db(abs(conv_d - dc))

%% Let's try freq space convolution again...
conv_d = freq_space_filter(d, W)

%% What if we replicate the freq space convolution instead of padding with zeros?
% Garbage....

p_freq = fftshift(fft2(pattern));
n_repeats = ceil(N / P);
W = repmat(p_freq, n_repeats, n_repeats);
W = W(1:512, 1:512);

figure()
plot_2d_db(abs(W))

d_conv2 = freq_space_filter(d, W);
figure()
image_gray(abs(d_conv2))



%%
conv_d_1 = conv2(d, w);
figure()
image_gray(conv_d)





%% What's the difference between FFT and BT?
Sxx_fft = fftshift(abs(fft2(d).^2));
R_xx_dpn = conv2(dpn, dpn, "full");
Sxx_bt = fftshift(abs(fft2(R_xx_dpn)));

figure()
plot_2d_db(Sxx_fft)
title("From fft")

figure()
plot_2d_db(Sxx_bt)
title("From BT")


%%
d_filt = ifft2(ifftshift(D));
d_est_image = abs(conv2(dc, d_filt, "full"));
d_est_image = d_est_image(1:512, 1:512);
d_est_image = d_est_image * mean(d, "all") / mean(d_est_image, "all");
figure()
image_gray(d_est_image)


%%
figure()
plot_2d_db(abs(d_filt))
